### PR TITLE
Parameterized Statement Support

### PR DESCRIPTION
**Pull request by bwarminski**
Love the project. I've been playing around with rqlite in a prototype that uses Java. This just adds the parameterized statement functionality for now. 

Any tips to get all tests passing on a a Macbook? It looks like they assume a certain environment set up or rqlite binary location.

### CODE REVIEW

**Comment by otoolep** [comment]
Thank you for your contribution! 

I'm not really much of a Java programmer, so don't have any advice on getting it running on a Macbook.

**Comment by otoolep** [comment]
I'm looking for someone to maintain this library, if you're interested.

**Comment by bwarminski** [comment]
> I'm not really much of a Java programmer

I'm not a very good one :) 

> I'm looking for someone to maintain this library, if you're interested.

Happy to give it a coat of paint and get it to match the Go client in functionality if you'd like. Long term, I may not be the best steward, but I'm prototyping it and LiteFS for some distributed data sets at work. If prototype succeeds, yes I think I could do this or find someone more opinionated about Java to help.

**Comment by otoolep** [comment]
Sounds good  -- thanks in advance for any contributions you make.

**Pull request merged**
